version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@wessberg/rollup-plugin-ts"
    versions:
    - 1.3.10
    - 1.3.11
    - 1.3.14
  - dependency-name: "@ideal-postcodes/jsutil"
    versions:
    - 4.0.1
    - 4.2.0
    - 4.3.1
    - 4.3.2
    - 4.3.4
    - 4.3.6
    - 4.3.7
    - 4.3.8
  - dependency-name: "@ideal-postcodes/api-fixtures"
    versions:
    - 1.3.0
  - dependency-name: rollup
    versions:
    - 2.39.0
    - 2.40.0
    - 2.41.2
    - 2.42.2
    - 2.45.1
  - dependency-name: cypress
    versions:
    - 6.6.0
    - 6.8.0
    - 7.0.1
  - dependency-name: "@rollup/plugin-commonjs"
    versions:
    - 17.1.0
    - 18.0.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
    - 7.13.8
    - 7.13.9
  - dependency-name: semantic-release
    versions:
    - 17.4.0
    - 17.4.1
    - 17.4.2
  - dependency-name: eslint
    versions:
    - 7.21.0
  - dependency-name: typescript
    versions:
    - 4.1.5
    - 4.2.2
  registries:
  - npm-registry-registry-npmjs-org
