services:
  db:
    image: mariadb:10.6
    volumes:
      - db-data:/var/lib/mysql/data
    env_file:
      - ./docker/.env
    ports:
      - 3306:3306
  web:
    build: .
    ports:
      - "3000:80"
    links:
      - db
    env_file:
      - ./docker/.env
    volumes:
      # Map extension files to the extension directory structure
      - ./src/admin/controller/module/ukaddresssearch.php:/var/www/html/extension/idealpostcodes/admin/controller/module/ukaddresssearch.php
      - ./src/admin/language/en-gb/module/ukaddresssearch.php:/var/www/html/extension/idealpostcodes/admin/language/en-gb/module/ukaddresssearch.php
      - ./src/admin/view/template/module/ukaddresssearch.twig:/var/www/html/extension/idealpostcodes/admin/view/template/module/ukaddresssearch.twig
      
      - ./src/catalog/controller/module/ukaddresssearch.php:/var/www/html/extension/idealpostcodes/catalog/controller/module/ukaddresssearch.php
      - ./src/catalog/language/en-gb/module/ukaddresssearch.php:/var/www/html/extension/idealpostcodes/catalog/language/en-gb/module/ukaddresssearch.php
      - ./src/catalog/view/theme/default/template/module/ukaddresssearch.twig:/var/www/html/extension/idealpostcodes/catalog/view/template/module/ukaddresssearch.twig
      
      # Asset files
      - ./src/catalog/view/javascript/opencart.js:/var/www/html/extension/idealpostcodes/catalog/view/javascript/opencart.js
      - ./src/catalog/view/stylesheet/ideal-postcodes-autocomplete.css:/var/www/html/extension/idealpostcodes/catalog/view/css/ideal-postcodes-autocomplete.css
      - ./src/catalog/view/stylesheet/ideal-postcodes-lookup.css:/var/www/html/extension/idealpostcodes/catalog/view/css/ideal-postcodes-lookup.css
      
      # Install file
      - ./src/install.json:/var/www/html/extension/idealpostcodes/install.json

      # OpenCart storage volume
      - "opencart-storage:/var/storage"
volumes:
  db-data:
  opencart-storage:
