name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - master

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
          
      - name: Launch OpenCart test environment
        run: make bootstrap

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_API_KEY: ${{ secrets.API_KEY }}
