name: CI

on:
  - push

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Launch OpenCart test environment
        run: make bootstrap

      - uses: cypress-io/github-action@v1
        env:
          CYPRESS_API_KEY: ${{ secrets.API_KEY }}
